name: "KoolSmart"
description: "My KoolSmart"
version: "0.1.0"
slug: "koolsmart_100"
panel_icon: mdi:lightbulb-on-80
init: false
ingress: true
host_network: true
ingress_port: 8489
startup: before
ports:
  8489/tcp: 8489
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
# image: "ghcr.io/home-assistant/{arch}-kool_smart"
